// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcMK6_7pqS-YAXgqwElTcRwmfrDx2CuZI',
    appId: '1:614408924683:web:69d71294605cfa2d05610e',
    messagingSenderId: '614408924683',
    projectId: 'organizationalapp',
    authDomain: 'organizationalapp.firebaseapp.com',
    storageBucket: 'organizationalapp.firebasestorage.app',
    measurementId: 'G-F20FVTJCP4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_EqBUaMT6jV46s1TkMRQWZnxxXZjou68',
    appId: '1:614408924683:android:74b90225191ea88805610e',
    messagingSenderId: '614408924683',
    projectId: 'organizationalapp',
    storageBucket: 'organizationalapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC281mwGJFICrstl6qUMx8NZeMFsxSVtQg',
    appId: '1:614408924683:ios:d68453ee6e5140e205610e',
    messagingSenderId: '614408924683',
    projectId: 'organizationalapp',
    storageBucket: 'organizationalapp.firebasestorage.app',
    iosBundleId: 'com.example.organizationalAppGroup1Csen268F25',
  );

}